### PR TITLE
ShippersInstruction: Request new Property 

### PR DESCRIPTION
**Pull request by liamforde**
I want this new property

### CODE REVIEW

**Comment by liamforde** [comment]
cool proposal

**Comment by liamforde** [comment]
[[TCF Official]]
---
I agree

**Comment by liamforde** [comment]
really like it!

**Comment by liamforde** [comment]
testing the spinner

**Comment by liamforde** [comment]
[[TCF Official]]
---
looks like it works pretty well!

**Comment by ktk** [comment]
Closing all broken pull-requests.

**Pull request closed without merging**
